package Management;

public class HospitalManagementSystem {
    private service.PatientService patientService;
    private service.DoctorService doctorService;
    private data_structures.priorityqueue.ERPriorityQueue erQueue;
    private undo.UndoManager undoManager;
    private data_structures.tree.HospitalDirectoryTree directoryTree;

    public HospitalManagementSystem() {
        this.undoManager = new undo.UndoManager();
        this.patientService = new service.PatientService(undoManager);
        this.doctorService = new service.DoctorService(undoManager);
        this.erQueue = new data_structures.priorityqueue.ERPriorityQueue(200);
        this.directoryTree = new data_structures.tree.HospitalDirectoryTree("Main Hospital");
    }



    // --- Patient operations ---
    // Create patient with autogenerated unique id
    public models.Patient createPatient(String name, int age, String gender) {
        int id = generateUniquePatientId();
        return patientService.addPatient(id, name, age, gender);
    }
    public models.Patient createPatient(int id,String name, int age, String gender) {
        return patientService.addPatient(id, name, age, gender);
    }


    public models.Patient removePatient(int id) {
        return patientService.removePatient(id);
    }

    public models.Patient findPatient(int id) {
        return patientService.getPatient(id);
    }

    public void addVisitRecord(int patientId, int doctorId, String description) {
        models.VisitRecord vr = new models.VisitRecord(patientId, doctorId, description, utils.TimeUtil.now());
        patientService.addVisitRecord(patientId, vr);
    }

    public void printPatientVisits(int patientId) {
        patientService.printVisits(patientId);
    }




    // --- Doctor operations ---
    public models.Doctor addDoctor(int id, String name, String department, String start, String end) {
        models.Doctor d = doctorService.addDoctor(id, name, department, start, end);
        // also add to directory tree under department
        data_structures.tree.GeneralTreeNode deptNode = directoryTree.search(department);
        if (deptNode == null) {
            deptNode = directoryTree.addDepartment(department);
        }
        directoryTree.addDoctor(deptNode, d);
        return d;
    }

    public models.Doctor removeDoctor(int id) {
        return doctorService.removeDoctor(id);
    }

    public models.Doctor findDoctor(int id) {
        return doctorService.getDoctor(id);
    }

    public void enqueuePatientToDoctor(int doctorId, int patientId) {
        doctorService.enqueuePatientToDoctor(doctorId, patientId);
    }

    public Object dequeueForDoctor(int doctorId) {
        return doctorService.dequeueFromDoctor(doctorId);
    }




    // --- Appointment operations ---
    public boolean createAppointment(int doctorId, int patientId, String time) {
        return doctorService.createAppointment(doctorId, patientId, time);
    }

    //This method returns Appointments for doctor ID
    public java.util.ArrayList<models.Appointment> listAppointmentsForDoctor(int doctorId) {
        return doctorService.getAppointmentsForDoctor(doctorId);
    }


    public boolean cancelAppointment(int doctorId, String time) {
        java.util.ArrayList<models.Appointment> list = doctorService.getAppointmentsForDoctor(doctorId);
        if (list == null) return false;

        for (int i = 0; i < list.size(); i++) {
            if (list.get(i).getTime().equals(time)) {
                list.remove(i);
                return true;
            }
        }
        return false;
    }


    // --- ER operations ---
    public void addERPatient(int patientId, int severity) {
        String now = utils.TimeUtil.now();
        models.ERPatient p = new models.ERPatient(patientId, severity, now);
        erQueue.add(p);
        // record check-in as undoable action for potential rollback
        undoManager.record(undo.ActionType.CHECKIN_PATIENT, p);
    }

    public models.ERPatient treatNextERPatient() {
        Object o = erQueue.treatNext();
        if (o == null) return null;
        return (models.ERPatient) o;
    }






    // --- Directory operations ---
    public data_structures.tree.GeneralTreeNode addDepartment(String name) {
        return directoryTree.addDepartment(name);
    }

    public data_structures.tree.GeneralTreeNode addDoctorToDepartment(String departmentName, int doctorId) {
        data_structures.tree.GeneralTreeNode dept = directoryTree.search(departmentName);
        if (dept == null) dept = directoryTree.addDepartment(departmentName);
        models.Doctor d = doctorService.getDoctor(doctorId);
        if (d == null) return null;
        return directoryTree.addDoctor(dept, d);
    }

    public void printDirectory() {
        directoryTree.printTree();
    }



    // --- Undo ---
    // Current undo implementation pops the last action and prints a short message.
    public void undoLastAction() {
        undo.UndoAction action = undoManager.undo();
        if (action == null) {
            System.out.println("No undoable actions left.");
            return;
        }

        System.out.println("Undoing action: " + action.getActionType());

        // Basic handling for some action types (non-exhaustive).
        switch (action.getActionType()) {
            case ADD_PATIENT:
                try {
                    models.Patient p = (models.Patient) action.getData();
                    patientService.removePatient(p.getId());
                    System.out.println("Removed patient created by last action: " + p.getId());
                } catch (Exception e) {
                    System.out.println("Could not undo ADD_PATIENT: " + e.getMessage());
                }
                break;
            case REMOVE_PATIENT:
                try {
                    models.Patient p = (models.Patient) action.getData();
                    // re-insert patient (no guaranteed original id conflict handling)
                    patientService.addPatient(p.getId(), p.getName(), p.getAge(), p.getGender());
                    System.out.println("Re-inserted patient: " + p.getId());
                } catch (Exception e) {
                    System.out.println("Could not undo REMOVE_PATIENT: " + e.getMessage());
                }
                break;
            case ADD_DOCTOR:
                try {
                    models.Doctor d = (models.Doctor) action.getData();
                    doctorService.removeDoctor(d.getId());
                    System.out.println("Removed doctor created by last action: " + d.getId());
                } catch (Exception e) {
                    System.out.println("Could not undo ADD_DOCTOR: " + e.getMessage());
                }
                break;
            case REMOVE_DOCTOR:
                try {
                    models.Doctor d = (models.Doctor) action.getData();
                    doctorService.addDoctor(d.getId(), d.getName(), d.getDepartment(), d.getWorkStart(), d.getWorkEnd());
                    System.out.println("Re-inserted doctor: " + d.getId());
                } catch (Exception e) {
                    System.out.println("Could not undo REMOVE_DOCTOR: " + e.getMessage());
                }
                break;
            case CHECKIN_PATIENT:
                // For ER check-in, try to remove one matching ERPatient (best-effort)
                try {
                    models.ERPatient ep = (models.ERPatient) action.getData();
                    // remove by matching patientId and arrivalTime — linear scan of heap not provided
                    System.out.println("NOTE: undo for ER check-in is best-effort and may not remove from queue.");
                } catch (Exception e) {
                    System.out.println("Could not undo CHECKIN_PATIENT: " + e.getMessage());
                }
                break;
            default:
                System.out.println("Undo action type not explicitly handled: " + action.getActionType());
        }
    }



    // --- Utilities ---
    private int generateUniquePatientId() {
        //getProjectSeed method returns project seed using student number.
        int base = (int) Math.abs((long) (utils.IDUtil.getProjectSeed() % 1_000_000L));
        int id = base;
        int attempts = 0;
        while (patientService.getPatient(id) != null && attempts < 10000) {
            id = base + utils.RandomGenerator.nextInt(1, 9999) + attempts;
            attempts++;
        }
        // final fallback
        if (patientService.getPatient(id) != null) {
            id = base + (int) System.currentTimeMillis() % 1_000_000;
        }
        return Math.abs(id);
    }



    // --- Getters for sub-systems ---
    public service.PatientService getPatientService() { return patientService; }
    public service.DoctorService getDoctorService() { return doctorService; }
    public data_structures.priorityqueue.ERPriorityQueue getErQueue() { return erQueue; }
    public undo.UndoManager getUndoManager() { return undoManager; }
    public data_structures.tree.HospitalDirectoryTree getDirectoryTree() { return directoryTree; }
}
